# studio-engine ships an OPT-IN motion/effects CSS layer (engine-motion.css).
#
# tailwindcss-rails' engines contract (Tailwindcss::Engines.bundle) auto-bundles
# ONLY the file named exactly `engine.css`, so it skips `engine-motion.css` BY
# CONSTRUCTION. We mirror that generation here: emit a gitignored companion
# entry `app/assets/builds/tailwind/<engine>_motion.css` that @imports the gem's
# engine-motion.css by its RESOLVED absolute path. application.css then adopts it
# with one stable relative import (`../builds/tailwind/studio_engine_motion`),
# so no gem version or machine gem-home is ever baked into committed source.
#
# Re-opening `tailwindcss:engines` is additive: this action runs alongside the
# gem's own bundler whenever :engines runs — and :engines is a prerequisite of
# tailwindcss:build / :watch (and, via assets:precompile, of production builds).
namespace :tailwindcss do
  task engines: :environment do
    FileUtils.mkdir_p(Rails.root.join("app/assets/builds/tailwind"))

    Rails::Engine.subclasses.select do |engine|
      engine.root.join("app/assets/tailwind/#{engine.engine_name}/engine-motion.css").exist?
    end.each do |engine|
      source = engine.root.join("app/assets/tailwind/#{engine.engine_name}/engine-motion.css")
      out    = Rails.root.join("app/assets/builds/tailwind/#{engine.engine_name}_motion.css")

      File.write(out, <<~TEMPLATE)
        /* DO NOT MODIFY THIS FILE, it was auto-generated by lib/tasks/tailwindcss_engine_motion.rake */

        @import "#{source}";
      TEMPLATE
    end
  end
end
