require "test_helper"

# /admin/style (StyleController#index) is studio-engine's living style guide: an
# admin-gated page that renders the shared UI primitives live inside the HOST's
# own application.html.erb layout. Turf Monster adopted it with studio-engine
# 0.18 — the gem bump plus the engine-motion.css import (generated by
# lib/tasks/tailwindcss_engine_motion.rake) that styles the motion/leveling
# specimens. These lock in that the page renders in TM's chrome for an admin,
# stays admin-gated, and carries all four engine specimen sections.
class AdminStylePageTest < ActionDispatch::IntegrationTest
  setup { @admin = users(:alex) }

  test "renders the design system page for an admin in TM chrome" do
    log_in_as(@admin)
    get admin_style_path

    assert_response :success
    assert_select "h1", text: "Style"

    # The version label proves the mounted engine's page is what rendered.
    # Asserted against Studio::VERSION so it survives future bumps.
    assert_includes @response.body, "studio-engine"
    assert_includes @response.body, "v#{Studio::VERSION}"

    # The four specimen sections render as sibling partials (theme/modals/
    # tricks/tasks). Each only appears if its partial rendered without error.
    assert_select "section#theme"
    assert_select "section#modals"
    assert_select "section#tricks"
    assert_select "section#tasks"
  end

  test "redirects a non-admin away from /admin/style" do
    log_in_as(users(:jordan))
    get admin_style_path

    assert_redirected_to root_path
  end
end
