require "test_helper"

# /admin/style (StyleController#index) is studio-engine's living style guide: an
# admin-gated page that renders the shared UI primitives live inside the HOST's
# own application.html.erb layout. Turf Monster adopted it with studio-engine
# 0.18 — the gem bump plus the engine-motion.css import (generated by
# lib/tasks/tailwindcss_engine_motion.rake) that styles the motion/leveling
# specimens. These lock in that the page renders in TM's chrome for an admin,
# stays admin-gated, and carries all four engine specimen sections.
class AdminStylePageTest < ActionDispatch::IntegrationTest
  setup { @admin = users(:alex) }

  test "renders the design system page for an admin in TM chrome" do
    log_in_as(@admin)
    get admin_style_path

    assert_response :success
    assert_select "h1", text: "Style"

    # The version label proves the mounted engine's page is what rendered.
    # Asserted against Studio::VERSION so it survives future bumps.
    assert_includes @response.body, "studio-engine"
    assert_includes @response.body, "v#{Studio::VERSION}"

    # The four specimen sections render as sibling partials (theme/modals/
    # tricks/tasks). Each only appears if its partial rendered without error.
    assert_select "section#theme"
    assert_select "section#modals"
    assert_select "section#tricks"
    assert_select "section#tasks"

    # TM is an on-chain app: config.features enables :web3 + :leveling, so the
    # engine's Web3 modal specimens and leveling tricks render ENABLED, not
    # capability-gated. Guards the studio.rb config.features fix — a revert would
    # grey these and re-add the badge.
    assert_no_match(/disabled on this app/, @response.body)

    # A SECOND PAIR LIVED HERE, RETIRED 2026-09-09:
    #   assert_match(/wallet:\s*true/) / assert_no_match(/wallet:\s*false/)
    # They read the seeded toggle state of the ENGINE'S Auth specimen, which was
    # a mirror of THIS APP's sign-in card and has been deleted — the engine ships
    # no auth card at all now, and this app cards its real one on its own host
    # section (app/views/style/host/_modals.html.erb).
    #
    # WHAT THEY ACTUALLY PROVED, and why the replacement is not the badge check
    # above: that pair turned true only when Studio.auth_method?(:wallet) AND
    # :web3 AND the solana-studio gem all resolved. The badge check covers the
    # FEATURES term alone. The term with no other witness here is the GEM — so
    # assert it the way the guide itself decides it, on a card that only becomes
    # a trigger when the gem resolves.
    #
    # `Connect wallet` renders from solana_studio/modals/_wallet_connect. Where
    # the gem is absent the engine deliberately keeps the card LISTED but strips
    # role="button" (an unregistered id would open an empty panel) and prints a
    # notice saying why. Both halves are asserted, because the listed-but-inert
    # state is exactly what a lost gem looks like.
    connect_card = @response.body[/<[^>]*aria-label="Open the Connect wallet modal"[^>]*>/]
    assert connect_card,
           "the engine's Connect wallet specimen is missing entirely — expected it listed " \
           "whether or not the gem resolves"
    assert_includes connect_card, 'role="button"',
                    "Connect wallet is listed but NOT a trigger, which is how the engine renders " \
                    "it when solana-studio does not resolve — this app bundles the gem"
    assert_no_match(/This app bundles no solana-studio/, @response.body,
                    "the guide thinks this app ships no solana-studio")
  end

  test "redirects a non-admin away from /admin/style" do
    log_in_as(users(:jordan))
    get admin_style_path

    assert_redirected_to root_path
  end
end
